### PR TITLE
#160086539 Build homepage layout

### PR DESCRIPTION
**Pull request by mashafrancis**
#### What does this PR do?
Creates the homepage layout
#### Description of Task to be completed?
Have the following the homepage:
1. Navigation header with logo
2. Banner image header
3. Menu categories
4. Footer section

#### What are the relevant pivotal tracker stories?
#160086539
#### Screenshots
(Screenshot 1)
screenshot at 2018-08-29 13-45-41

(Screenshot 2)
screenshot at 2018-08-29 13-46-00

### CODE REVIEW

**Review by Derrickkip — APPROVED** [review]
Nice UI

**Comment by SimonAwiti** [comment]
nice UI man...

**Comment by davishooly** [comment]
nice design its eye catching

**Comment by Darius-Ndubi** [comment]
Great UI, when go I order.

**Comment by H-Rigga** [comment]
This looks nice

**Comment by kmwangemi** [comment]
Nice one

**Comment by PromasterGuru** [comment]
Awesome :)

**Comment by gwako94** [comment]
Awesome UI

**Comment by Chell0** [comment]
I loooove this

**Comment by bettblake08** [comment]
This is impressive. Very attractive landing page

**Comment by mashafrancis** [comment]
Thank you guys. I appreciate.

**Comment by danielotieno** [comment]
Great Work!

**Comment by evans17** [comment]
great work

**Comment by EmmanuelMuchiri** [comment]
Awesome

**Pull request merged**
